Repository databrickslabs/lsql, pull requests merged in 2024-09, with the labels that each got.

#284 Fix unit test for export to zipped csv
  tests/unit/test_dashboards.py
Labels: internal

#285 Format code
  tests/integration/test_structs.py
Labels: internal

#283 Retry deploy schema on `InternalError`
  src/databricks/labs/lsql/deployment.py
Labels: internal

#286 Skip integration test `test_appends_complex_types`
  tests/integration/test_structs.py
Labels: internal

#288 Format code
  src/databricks/labs/lsql/deployment.py
  tests/integration/test_structs.py
Labels: internal

#289 Bugfix: `MockBackend` wasn't mocking `savetable` properly when the mode is `append`
  src/databricks/labs/lsql/backends.py
  tests/unit/test_backends.py
Labels: bug

#296 Set catalog on `SchemaDeployer` to overwrite the default `hive_metastore`
  pyproject.toml
  src/databricks/labs/lsql/backends.py
  src/databricks/labs/lsql/core.py
  src/databricks/labs/lsql/deployment.py
  tests/integration/test_backends.py
  tests/integration/test_deployment.py
  tests/unit/test_deployment.py
Labels: enhancement
